### APP ###
app:
  # Resources
  resources:
    prefixes-file: /data/prefixes.csv
  # Kafka
  kafka:
    streams:
      source-topic: persons
      sink-topic: greetings
      state-store: persons
      processor: personProcessor
      punctuator-schedule: PT10S
      processing-delay: PT60S

### SPRING ###
spring:
  # Application
  application:
    name: spring-boot-kafka-cqrs-backend
  # Profiles
  profiles:
    active: development
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DURATIONS_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
  # Kafka
  kafka:
    streams:
      application-id: ${spring.application.name}-streams
      properties:
        "spring.json.trusted.packages": "com.onlyteo.sandbox.*"
