version: "3.7"

services:
  sandbox.postgres:
    image: postgres
    container_name: sandbox.postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: G4nd4lf
    ports:
      - "5432:5432"
    volumes:
      - ./resources/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - sandbox.postgres.data:/var/lib/postgresql/data
    networks:
      - sandbox.postgres

volumes:
  sandbox.postgres.data:
    name: sandbox.postgres.data

networks:
  sandbox.postgres:
    name: sandbox.postgres
