### SERVICES ###
services:
  sandbox.postgres:
    image: postgres
    container_name: sandbox.postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: G4nd4lf
    ports:
      - "5432:5432"
    volumes:
      - ./resources/initdb.d:/docker-entrypoint-initdb.d
      - sandbox.postgres.data:/var/lib/postgresql/data
    networks:
      - sandbox.postgres

### VOLUMES ###
volumes:
  sandbox.postgres.data:
    name: sandbox.postgres.data

### NETWORKS ###
networks:
  sandbox.postgres:
    name: sandbox.postgres
