CREATE TABLE PERSONS
(
    ID    INTEGER     NOT NULL AUTO_INCREMENT,
    NAME  VARCHAR(50) NOT NULL,
    COUNT INTEGER     NOT NULL,
    CONSTRAINT PERSONS_PK PRIMARY KEY (ID),
    CONSTRAINT PERSONS_NAME_UC UNIQUE (NAME)
);