{
 "title": "sandbox.ktor-otel-observability-backend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "1e0df05b", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "sandbox.ktor-otel-observability-frontend-api"
       ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": []
      }
     ],
     "groupBy": [
      { "id": "7498f9d6", "scope": "span" }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ktor_http_server_requests_seconds_bucket{instance=\"sandbox.ktor-otel-observability-backend:8080\", route!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{area=\"heap\", instance=\"sandbox.ktor-otel-observability-backend:8080\"})",
     "legendFormat": "JVM Used Heap"
    },
    {
     "expr": "sum by(instance) (jvm_memory_max_bytes{area=\"heap\", instance=\"sandbox.ktor-otel-observability-backend:8080\"})",
     "legendFormat": "JVM Max Heap"
    }
   ]
  },
  {
   "title": "JVM GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{instance=\"sandbox.ktor-otel-observability-backend:8080\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}