### APP ###
app:
  # Security
  security:
    # Paths that should be without security
    whitelisted-paths:
      - /webjars/**
      - /assets/**
      - /favicon.ico
      - /error

### SPRING ###
spring:
  # Application
  application:
    name: spring-boot-oauth2-token-relay-frontend-api
  # Profiles
  profiles:
    active: development
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    datetime:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
