### APP ###
app:
  # Security
  security:
    users:
      - username: john.doe
        password: abcd1234
        roles:
          - USER
    keys:
      - key-id: 7530e691-49f8-4284-bc07-11825cb23b50
        public-key-location: classpath:keys/public.pem
        private-key-location: classpath:keys/private.pem
    whitelisted-paths:
      - /webjars/**
      - /assets/**
      - /favicon.ico
      - /error
      - /register

### Spring ###
spring:
  # Application
  application:
    name: spring-boot-oauth2-authorization-server-extended-authorization-server
  # Messages
  messages:
    basename: locale/messages
  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sandbox;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  # Security
  security:
    oauth2:
      authorizationserver:
        client:
          generic-client:
            registration:
              client-id: generic-client
              client-secret: "{noop}abcd1234"
              authorization-grant-types:
                - authorization_code
                - refresh_token
              scopes:
                - openid
                - profile
                - roles
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/generic-client
              client-authentication-methods:
                - client_secret_basic

### Logging ###
logging:
  level:
    root: INFO
    com.onlyteo: DEBUG

### Server ###
server:
  port: 8888
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false
