version: "3.7"

services:
  sandbox.kafka:
    image: confluentinc/cp-kafka:latest
    container_name: sandbox.kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: "INTERNAL://sandbox.kafka:29092,CONTROLLER://sandbox.kafka:29093,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://sandbox.kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@sandbox.kafka:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: "PMntZ445QqCTKnIDecTkcg"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    ports:
      - "9092:9092"
    volumes:
      - kafka.secrets:/etc/kafka/secrets
      - kafka.data:/var/lib/kafka/data
    networks:
      - kafka

volumes:
  kafka.secrets:
    name: sandbox.kafka.secrets
  kafka.data:
    name: sandbox.kafka.data

networks:
  kafka:
    name: sandbox.kafka
