### APP ###
app:
  # Resources
  resources:
    prefixes-file: /data/prefixes.csv
  # Kafka
  kafka:
    streams:
      source-topic: cdc.source.sandbox.persons
      sink-topic: greetings
      state-store: persons
      processor: personProcessor
      punctuator-schedule: PT10S
      processing-delay: PT60S

### SPRING ###
spring:
  # Application
  application:
    name: spring-boot-kafka-cdc-backend
  # Profiles
  profiles:
    active: development
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DURATIONS_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
  # Kafka
  kafka:
    consumer:
      client-id: ${spring.application.name}-consumer
      group-id: ${spring.application.name}-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "com.onlyteo.sandbox.*"
