### SPRING ###
spring:
  # Kafka
  kafka:
    consumer:
      bootstrap-servers:
        - "localhost:9092"

### LOGGING ###
logging:
  # Level
  level:
    org.apache.kafka: WARN
    org.springframework: INFO
    com.onlyteo: DEBUG

### SERVER ###
server:
  port: 8081
