-- USERS
CREATE TABLE IF NOT EXISTS USERS
(
    USERNAME VARCHAR(200) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(500) NOT NULL,
    ENABLED  BOOLEAN      NOT NULL
);

-- AUTHORITIES
CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    USERNAME  VARCHAR(200) NOT NULL,
    AUTHORITY VARCHAR(50)  NOT NULL,
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME),
    CONSTRAINT USERNAME_AUTHORITY UNIQUE (USERNAME, AUTHORITY)
);
