### SPRING ###
spring:
  # Kafka
  kafka:
    bootstrap-servers:
      - "localhost:9092"

### LOGGING ###
logging:
  # Level
  level:
    root: INFO
    com.onlyteo: DEBUG
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.streams.StreamsConfig: WARN

### SERVER ###
server:
  port: 8081
  error:
    include-stacktrace: ALWAYS
