### APP ###
app:
  kafka:
    producer:
      target-topic: persons
    consumer:
      source-topic: greetings

### SPRING ###
spring:
  # Application
  application:
    name: spring-boot-kafka-cqrs-frontend-api
  # Profiles
  profiles:
    active: development
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DURATIONS_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
  # Kafka
  kafka:
    consumer:
      client-id: ${spring.application.name}-consumer
      group-id: ${spring.application.name}-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "com.onlyteo.sandbox.*"
    producer:
      client-id: ${spring.application.name}-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
