### SERVICES ###
services:
  sandbox.mysql:
    image: mysql:8.0 # Must use MySQL version < 8.4 until DBZ-7838 is fixed - https://issues.redhat.com/browse/DBZ-7838
    container_name: sandbox.mysql
    environment:
      MYSQL_USER: sandbox
      MYSQL_PASSWORD: G4nd4lf
      MYSQL_DATABASE: sandbox
      MYSQL_ROOT_PASSWORD: G4nd4lf
    command: --lower_case_table_names=1 --log-bin=bin.log --log-bin-index=bin.log.index --binlog_do_db=sandbox
    ports:
      - "3306:3306"
    volumes:
      - ./resources/initdb.d:/docker-entrypoint-initdb.d
      - sandbox.mysql.conf:/etc/mysql/conf.d
      - sandbox.mysql.data:/var/lib/mysql
    networks:
      - sandbox.mysql

### VOLUMES ###
volumes:
  sandbox.mysql.conf:
    name: sandbox.mysql.conf
  sandbox.mysql.data:
    name: sandbox.mysql.data

### NETWORKS ###
networks:
  sandbox.mysql:
    name: sandbox.mysql
