### APP ###
app:
  # Security
  security:
    whitelisted-paths:
      - /webjars/**
      - /assets/**
      - /favicon.ico
      - /error

### Spring ###
spring:
  # Application
  application:
    name: spring-boot-oauth2-authorization-server-extended-client
  # Profiles
  profiles:
    active: local
  # Messages
  messages:
    basename: locale/messages
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DURATIONS_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
