### APP ###
app:
  integrations:
    backend:
      url: http://localhost:8081

### SPRING ###
spring:
  # Security
  security:
    oauth2:
      client:
        registration:
          sandbox-frontend:
            provider: spring-authorization-server
            client-id: sandbox-frontend
            client-secret: G4nd4lf
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - openid
              - profile
              - roles
            redirect-uri: http://localhost:3000/login/oauth2/code/sandbox-frontend # Use frontend host to allow login flow to go through browser
          sandbox-backend:
            provider: spring-authorization-server
            client-id: sandbox-backend
            client-secret: G4nd4lf
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            client-authentication-method: client_secret_basic
            scope:
              - greetings:read
        provider:
          spring-authorization-server:
            issuer-uri: http://127.0.0.1:8888 # Use IP to avoid session cookie collision

### LOGGING ###
logging:
  level:
    root: INFO
    com.onlyteo: DEBUG

### SERVER ###
server:
  port: 8080
  error:
    include-stacktrace: ALWAYS
